In [1]:
import pandas as pd

In [2]:
df=  pd.read_excel("fonepay_transaction_detail.xlsx")

In [3]:
df.head()

,_airbyte_ab_id,_airbyte_emitted_at,id,mti_number,initiated_by,txn_trace_id,fonepay_charge,fonepay_status,initiated_date,request_info_id,...,fonepay_service_code,fonepay_response_code,fonepay_transaction_status,transaction_status_checked,fonepay_transaction_remarks,fonepay_response_description,transaction_status_checked_date,_airbyte_additional_properties,source_file_path,updated_at
0,59d267c1-6ad3-40fc-99f6-645216231d27,2024-08-06 07:20:29.848,1,NaN,NaN,NaN,NaN,7,NaN,2873,...,EMERCHANT,-6,BANK_EXCEPTION,NaN,NaN,Internal Server Error,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:22.094
1,3c9feb78-ec3f-4612-b80b-e797d928fcf9,2024-08-06 07:20:29.848,2,NaN,NaN,NaN,NaN,7,NaN,2874,...,EMERCHANT,-6,BANK_EXCEPTION,NaN,NaN,Internal Server Error,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:22.094
2,ea076d84-3f3e-466a-ba8e-148290d0eb76,2024-08-06 07:20:29.848,3,12345678.0,NaN,GLBBNPKA:2875,10.0,1,NaN,2875,...,EMERCHANT,RES0000,NaN,0.0,NaN,NaN,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:22.094
3,d6421b60-6580-4abd-8712-9f5e05a32611,2024-08-06 07:20:29.848,4,12345678.0,NaN,GLBBNPKA:2962,10.0,1,NaN,2962,...,EMERCHANT,RES0000,NaN,0.0,NaN,NaN,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:22.094
4,e3be9245-a3dd-4f25-8442-e3e0c52c48dc,2024-08-06 07:20:29.848,5,12345678.0,NaN,GLBBNPKA:2963,10.0,1,NaN,2963,...,EMERCHANT,RES0000,NaN,0.0,NaN,NaN,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:22.094