In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('limit_node_history_table.xlsx')
df.head()

,liab,ts_cnt,bank_id,end_date,cont_liab,lchg_time,rcre_time,sanct_lim,fruct_liab,start_date,...,secured_liab,treasury_liab,user_maint_liab,limit_crncy_code,bg_effective_liab,util_limit_fund_based,util_limit_non_fund_based,treasury_liab_from_children,user_maint_liab_from_children,updated_at
0,0.0,4,1,2009-03-24T00:00:00.000000,1970496.0,2009-03-25T18:51:26,2009-01-25T17:59:23,2060000.0,0.0,2009-01-25T00:00:00.000000,...,0,NaN,0,NPR,0,0,0.0,NaN,0,2024-08-07 06:53:51.932
1,0.0,2,1,2010-06-21T00:00:00.000000,0.0,2010-06-22T16:51:49,2009-03-25T18:51:26,2060000.0,0.0,2009-03-25T00:00:00.000000,...,0,NaN,0,NPR,0,0,0.0,NaN,0,2024-08-07 06:53:51.932
2,0.0,2,1,2010-06-22T00:00:00.000000,0.0,2010-06-23T12:23:26,2010-06-22T16:51:49,1210000.0,0.0,2010-06-22T00:00:00.000000,...,0,NaN,0,NPR,0,0,0.0,NaN,0,2024-08-07 06:53:51.932
3,0.0,1,1,2010-10-03T00:00:00.000000,1209132.5,2010-10-04T16:03:38,2010-06-23T12:23:26,1210000.0,0.0,2010-06-23T00:00:00.000000,...,0,NaN,0,NPR,0,0,0.0,NaN,0,2024-08-07 06:53:51.932
4,0.0,1,1,2010-11-18T00:00:00.000000,1209132.5,2010-11-19T13:46:06,2010-10-04T16:03:38,1210000.0,0.0,2010-10-04T00:00:00.000000,...,0,NaN,0,NPR,0,0,0.0,NaN,0,2024-08-07 06:53:51.932

In [3]:
print(len(df))

1279

In [3]:
df.to_csv('limit_node_history_table_masked.csv', index=False)