In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_excel('province.xlsx')
df.head()

,_airbyte_ab_id,_airbyte_emitted_at,SOL_ID,HUB_NAME,BRANCH_NAME,BR_OPN_DATE,CLUSTER_NAME,PROVINCE_NAME,SUB_PROVINCIAL,_airbyte_additional_properties,source_file_path,updated_at
0,065a6581-4a6e-4e86-a0d7-265e67c0d867,2024-08-05 09:11:03.365,00,Registered Office,Head Office,2020-04-03T00:00:00.000000,Registered Office,Registered Office,Registered Office,NaN,s3a://ai360nica/data/bronze/oracle/cbs/CUSTOM/...,2024-08-07 06:59:45.556
1,fa9380fc-9b88-43e7-a5ee-a0561ea02d8b,2024-08-05 09:11:03.365,01,Bagmati Province,Tripureswor,2020-04-04T00:00:00.000000,Ujjwal Rimal,Province 3,Bagmati 5,NaN,s3a://ai360nica/data/bronze/oracle/cbs/CUSTOM/...,2024-08-07 06:59:45.556
2,06a26fb9-71c0-40a8-830d-1cb54efd65cf,2024-08-05 09:11:03.365,02,Koshi Province,Biratnagar,2020-04-05T00:00:00.000000,Diwakar Bhattarai,Province 1,Koshi 1,NaN,s3a://ai360nica/data/bronze/oracle/cbs/CUSTOM/...,2024-08-07 06:59:45.556
3,a7a25db6-0de2-4603-b90c-fa9bdbe89323,2024-08-05 09:11:03.365,03,Bagmati Province,Jawalakhel,2020-04-06T00:00:00.000000,Ganesh Paudel,Province 3,Bagmati 8,NaN,s3a://ai360nica/data/bronze/oracle/cbs/CUSTOM/...,2024-08-07 06:59:45.556
4,6deb1039-80ce-439c-ab06-04fcac20dd4e,2024-08-05 09:11:03.365,04,Koshi Province,Itahari,2020-04-07T00:00:00.000000,Dasarath Parajuli,Province 1,Koshi 2,NaN,s3a://ai360nica/data/bronze/oracle/cbs/CUSTOM/...,2024-08-07 06:59:45.556

In [20]:
df_male = pd.read_csv('../../crmuser/account/male.csv')
df_male.head()
print(len(df_male))

6213

In [24]:
nepali_surnames = [
    'Thapa', 'Poudel', 'Acharya', 'Adhikari', 'Bhandari', 
    'Bhattarai', 'Dahal', 'Gurung', 'Karki', 'Khadka',
    'Lama', 'Limbu', 'Magar', 'Maharjan', 'Neupane',
    'Pandey', 'Rai', 'Rana', 'Regmi', 'Sharma',
    'Shrestha', 'Tamang', 'Thakuri', 'Timalsina', 'Yadav'
]
df_male['last_name'] = np.random.choice(nepali_surnames, size=len(df_male))
sampled_rows = df_male.sample(n=361, random_state=42) 
print(len(sampled_rows))
sampled_rows.head()

361

     cust_first_name last_name
4570           Sahil   Thakuri
2273             Jen     Thapa
5350            Smit   Thakuri
3353          Nirvan    Khadka
167             Abid  Shrestha

In [23]:
df = df.drop(['_airbyte_ab_id', '_airbyte_emitted_at',"source_file_path","_airbyte_additional_properties"], axis=1)
df.head()

,SOL_ID,HUB_NAME,BRANCH_NAME,BR_OPN_DATE,CLUSTER_NAME,PROVINCE_NAME,SUB_PROVINCIAL,updated_at
0,00,Registered Office,Head Office,2020-04-03T00:00:00.000000,Registered Office,Registered Office,Registered Office,2024-08-07 06:59:45.556
1,01,Bagmati Province,Tripureswor,2020-04-04T00:00:00.000000,Ujjwal Rimal,Province 3,Bagmati 5,2024-08-07 06:59:45.556
2,02,Koshi Province,Biratnagar,2020-04-05T00:00:00.000000,Diwakar Bhattarai,Province 1,Koshi 1,2024-08-07 06:59:45.556
3,03,Bagmati Province,Jawalakhel,2020-04-06T00:00:00.000000,Ganesh Paudel,Province 3,Bagmati 8,2024-08-07 06:59:45.556
4,04,Koshi Province,Itahari,2020-04-07T00:00:00.000000,Dasarath Parajuli,Province 1,Koshi 2,2024-08-07 06:59:45.556

In [25]:
df["CLUSTER_NAME"] = sampled_rows["cust_first_name"].values + " " + sampled_rows["last_name"].values
df.head()

,SOL_ID,HUB_NAME,BRANCH_NAME,BR_OPN_DATE,CLUSTER_NAME,PROVINCE_NAME,SUB_PROVINCIAL,updated_at
0,00,Registered Office,Head Office,2020-04-03T00:00:00.000000,Sahil Thakuri,Registered Office,Registered Office,2024-08-07 06:59:45.556
1,01,Bagmati Province,Tripureswor,2020-04-04T00:00:00.000000,Jen Thapa,Province 3,Bagmati 5,2024-08-07 06:59:45.556
2,02,Koshi Province,Biratnagar,2020-04-05T00:00:00.000000,Smit Thakuri,Province 1,Koshi 1,2024-08-07 06:59:45.556
3,03,Bagmati Province,Jawalakhel,2020-04-06T00:00:00.000000,Nirvan Khadka,Province 3,Bagmati 8,2024-08-07 06:59:45.556
4,04,Koshi Province,Itahari,2020-04-07T00:00:00.000000,Abid Shrestha,Province 1,Koshi 2,2024-08-07 06:59:45.556

In [26]:
df.loc[0, "CLUSTER_NAME"] = "Registered Office"
df.head()

,SOL_ID,HUB_NAME,BRANCH_NAME,BR_OPN_DATE,CLUSTER_NAME,PROVINCE_NAME,SUB_PROVINCIAL,updated_at
0,00,Registered Office,Head Office,2020-04-03T00:00:00.000000,Registered Office,Registered Office,Registered Office,2024-08-07 06:59:45.556
1,01,Bagmati Province,Tripureswor,2020-04-04T00:00:00.000000,Jen Thapa,Province 3,Bagmati 5,2024-08-07 06:59:45.556
2,02,Koshi Province,Biratnagar,2020-04-05T00:00:00.000000,Smit Thakuri,Province 1,Koshi 1,2024-08-07 06:59:45.556
3,03,Bagmati Province,Jawalakhel,2020-04-06T00:00:00.000000,Nirvan Khadka,Province 3,Bagmati 8,2024-08-07 06:59:45.556
4,04,Koshi Province,Itahari,2020-04-07T00:00:00.000000,Abid Shrestha,Province 1,Koshi 2,2024-08-07 06:59:45.556

In [27]:
df.to_csv('province_masked.csv', index=False)