In [1]:
import pandas as pd

In [7]:
df=  pd.read_excel("login_device_info.xlsx")
df.head()

,_airbyte_ab_id,_airbyte_emitted_at,id,os_type,device_id,fcm_web_id,gcm_reg_id,version_id,customer_id,gcm_enabled,...,last_modified_by,customer_login_id,gcm_activation_at,login_device_mode,last_modified_date,device_extra_details,device_id_updated_at,_airbyte_additional_properties,source_file_path,updated_at
0,fda43d74-e7aa-49bf-a1c9-02e84e585cda,2024-08-06 07:20:29.848,1,iOS,753761C2-3C6F-4903-A449-A87708584633,NaN,NaN,3.0.0,298,N,...,NaN,298,NaN,D,NaN,"{""appBuildNumber"":""150"",""iOSVersion"":""17.5.1"",...","Row(member0=Timestamp('2024-07-17 10:12:11'), ...",NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:24.929
1,1ac1a6ad-803c-45ad-9b6e-65fa81f9f325,2024-08-06 07:20:29.848,2,iOS,NaN,NaN,NaN,3.0.0,140,N,...,NaN,140,NaN,D,NaN,"{""model"":""iPhone"",""manufacturer"":""Apple Inc"",""...","Row(member0=Timestamp('2024-04-03 13:12:58'), ...",NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:24.929
2,978924b1-eaa3-48d2-a200-48999e4dfc26,2024-08-06 07:20:29.848,3,iOS,NaN,NaN,NaN,3.0.0,149,N,...,NaN,149,NaN,D,NaN,"{""appBuildNumber"":""143"",""appVersion"":""6.6.142""...","Row(member0=Timestamp('2024-03-07 10:32:34'), ...",NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:24.929
3,a80c9db9-df8f-4069-91d5-c80bf3a88eb7,2024-08-06 07:20:29.848,4,Android,389fbd92d8d03ebf,NaN,NaN,3.0.0,1313,N,...,NaN,1313,NaN,D,"Row(member0=Timestamp('2024-01-30 16:38:53'), ...","{""androidVersion"":""14"",""appVersionCode"":""755"",...","Row(member0=Timestamp('2024-03-18 12:21:18'), ...",NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:24.929
4,d7df2b18-44e4-4d06-854c-502a4c40b3ea,2024-08-06 07:20:29.848,5,Android,00000000-146f-3c0e-0000-000066c0f7ce,NaN,NaN,3.0.0,1130,N,...,NaN,1130,NaN,D,NaN,"{""androidVersion"":""8.0.0"",""appVersionCode"":""77...","Row(member0=Timestamp('2024-07-22 14:35:18'), ...",NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:24.929

In [8]:
df = df.drop(['_airbyte_ab_id', '_airbyte_emitted_at',"source_file_path","_airbyte_additional_properties"], axis=1)
print(df.shape)
df.head()

(44, 18)

,id,os_type,device_id,fcm_web_id,gcm_reg_id,version_id,customer_id,gcm_enabled,device_model,email_address,last_modified_by,customer_login_id,gcm_activation_at,login_device_mode,last_modified_date,device_extra_details,device_id_updated_at,updated_at
0,1,iOS,753761C2-3C6F-4903-A449-A87708584633,NaN,NaN,3.0.0,298,N,NaN,NaN,NaN,298,NaN,D,NaN,"{""appBuildNumber"":""150"",""iOSVersion"":""17.5.1"",...","Row(member0=Timestamp('2024-07-17 10:12:11'), ...",2024-08-07 07:05:24.929
1,2,iOS,NaN,NaN,NaN,3.0.0,140,N,NaN,NaN,NaN,140,NaN,D,NaN,"{""model"":""iPhone"",""manufacturer"":""Apple Inc"",""...","Row(member0=Timestamp('2024-04-03 13:12:58'), ...",2024-08-07 07:05:24.929
2,3,iOS,NaN,NaN,NaN,3.0.0,149,N,NaN,NaN,NaN,149,NaN,D,NaN,"{""appBuildNumber"":""143"",""appVersion"":""6.6.142""...","Row(member0=Timestamp('2024-03-07 10:32:34'), ...",2024-08-07 07:05:24.929
3,4,Android,389fbd92d8d03ebf,NaN,NaN,3.0.0,1313,N,Android,NaN,NaN,1313,NaN,D,"Row(member0=Timestamp('2024-01-30 16:38:53'), ...","{""androidVersion"":""14"",""appVersionCode"":""755"",...","Row(member0=Timestamp('2024-03-18 12:21:18'), ...",2024-08-07 07:05:24.929
4,5,Android,00000000-146f-3c0e-0000-000066c0f7ce,NaN,NaN,3.0.0,1130,N,Android,NaN,NaN,1130,NaN,D,NaN,"{""androidVersion"":""8.0.0"",""appVersionCode"":""77...","Row(member0=Timestamp('2024-07-22 14:35:18'), ...",2024-08-07 07:05:24.929

In [9]:
df.to_csv("login_device_info_masked.csv", index=False)