In [2]:
import pandas as pd

In [4]:
df=  pd.read_excel("merchant_group.xlsx")
df.head()

,_airbyte_ab_id,_airbyte_emitted_at,id,code,icon,active,group_name,offer_text,sort_order,description,unicode_name,display_position,unicode_description,_airbyte_additional_properties,source_file_path,updated_at
0,4f1626ef-285a-4abe-a690-30de20eb5be4,2024-08-06 07:20:29.848,1,MPAY,merchant-group/bill-payment.png,Y,Credit Card,NaN,0,Bill Payment to registered merchants,NaN,"mainmenu,payment",NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:25.979
1,97e0b688-702e-4336-92d4-9f341363fc8a,2024-08-06 07:20:29.848,2,TOPUP,other-payments.png,Y,Topup,NaN,4,Topup payment,NaN,payment,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:25.979
2,926b42fc-ffb1-4ad4-85db-6dde216b3b40,2024-08-06 07:20:29.848,3,RC,card.png,Y,Recharge Card,NaN,5,Recharge various recharge vouchers,NaN,payment,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:25.979
3,ecd8566c-50a1-40c8-92d0-1a0881f494e6,2024-08-06 07:20:29.848,4,WAL,wallet-topup.png,Y,Load Wallet,NaN,2,Load Wallet,NaN,payment,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:25.979
4,c58bf908-3c03-4e93-be6b-b214f319daa9,2024-08-06 07:20:29.848,5,DATA_PACKAGE,data-pack.png,Y,Data Package,NaN,6,Data Package,NaN,payment,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:25.979

In [5]:
df = df.drop(['_airbyte_ab_id', '_airbyte_emitted_at',"source_file_path","_airbyte_additional_properties"], axis=1)
print(df.shape)
df.head()

(7, 12)

,id,code,icon,active,group_name,offer_text,sort_order,description,unicode_name,display_position,unicode_description,updated_at
0,1,MPAY,merchant-group/bill-payment.png,Y,Credit Card,NaN,0,Bill Payment to registered merchants,NaN,"mainmenu,payment",NaN,2024-08-07 07:05:25.979
1,2,TOPUP,other-payments.png,Y,Topup,NaN,4,Topup payment,NaN,payment,NaN,2024-08-07 07:05:25.979
2,3,RC,card.png,Y,Recharge Card,NaN,5,Recharge various recharge vouchers,NaN,payment,NaN,2024-08-07 07:05:25.979
3,4,WAL,wallet-topup.png,Y,Load Wallet,NaN,2,Load Wallet,NaN,payment,NaN,2024-08-07 07:05:25.979
4,5,DATA_PACKAGE,data-pack.png,Y,Data Package,NaN,6,Data Package,NaN,payment,NaN,2024-08-07 07:05:25.979

In [7]:
df.to_csv("merchant_group_masked.csv", index=False)