In [1]:
import pandas as pd

In [3]:
df=  pd.read_excel("merchant.xlsx")
df.head()

,_airbyte_ab_id,_airbyte_emitted_at,id,icon,active,mnemonic,has_limit,created_by,offer_text,service_id,...,payable_limit_type,account_branch_code,redirect_to_fonepay,merchant_description,allow_counter_payment,merchant_category_code_id,unicode_merchant_description,_airbyte_additional_properties,source_file_path,updated_at
0,b9af1738-a102-4442-9f75-fe8757d71b63,2024-08-06 07:20:29.848,2,ntc.png,Y,NTPOS,Y,1,NaN,10,...,F,0,N,NT Postpaid Topup,N,NaN,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:25.427
1,2beb3769-67ce-4711-b72b-d19e810697d9,2024-08-06 07:20:29.848,3,ncell.png,Y,NCELL,Y,1,NaN,8,...,R,0,N,Ncell Topup,N,NaN,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:25.427
2,7568ff19-3dee-45b0-a05d-09232d0ca9b3,2024-08-06 07:20:29.848,4,esewa-icon.png,Y,ESEWA,Y,1,NaN,26,...,R,1,N,eSewa Load,N,NaN,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:25.427
3,de61545c-da20-4358-8782-2777e997f1da,2024-08-06 07:20:29.848,5,fonepay-direct.png,Y,FPIBT,N,1,NaN,4,...,R,1,N,Fonepay InterBank Transfer,N,NaN,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:25.427
4,2a5594cf-14e4-4951-8be9-4d45b7bb3d90,2024-08-06 07:20:29.848,6,fonepay-direct.png,Y,FPMP,N,1,NaN,5,...,R,0,N,Fonepay Merchant Payment,N,NaN,NaN,NaN,s3a://ai360nica/data/bronze/mysql/mobile_banki...,2024-08-07 07:05:25.427

In [4]:
df = df.drop(['_airbyte_ab_id', '_airbyte_emitted_at',"source_file_path","_airbyte_additional_properties"], axis=1)
print(df.shape)
df.head()

(50, 34)

,id,icon,active,mnemonic,has_limit,created_by,offer_text,service_id,sort_order,instruction,...,merchant_group_id,last_modified_date,payable_limit_type,account_branch_code,redirect_to_fonepay,merchant_description,allow_counter_payment,merchant_category_code_id,unicode_merchant_description,updated_at
0,2,ntc.png,Y,NTPOS,Y,1,NaN,10,3,Please enter your NT Postpaid mobile number an...,...,2.0,"Row(member0=Timestamp('2019-02-01 08:32:11'), ...",F,0,N,NT Postpaid Topup,N,NaN,NaN,2024-08-07 07:05:25.427
1,3,ncell.png,Y,NCELL,Y,1,NaN,8,4,Please enter your NCELL Mobile Number and sele...,...,2.0,"Row(member0=Timestamp('2019-02-01 08:31:59'), ...",R,0,N,Ncell Topup,N,NaN,NaN,2024-08-07 07:05:25.427
2,4,esewa-icon.png,Y,ESEWA,Y,1,NaN,26,1,"Please enter your Esewa Id, select amount and ...",...,4.0,"Row(member0=Timestamp('2018-11-11 13:21:38'), ...",R,1,N,eSewa Load,N,NaN,NaN,2024-08-07 07:05:25.427
3,5,fonepay-direct.png,Y,FPIBT,N,1,NaN,4,2,NaN,...,1.0,NaN,R,1,N,Fonepay InterBank Transfer,N,NaN,NaN,2024-08-07 07:05:25.427
4,6,fonepay-direct.png,Y,FPMP,N,1,NaN,5,3,NaN,...,1.0,NaN,R,0,N,Fonepay Merchant Payment,N,NaN,NaN,2024-08-07 07:05:25.427

In [5]:
df.to_csv("merchant_masked.csv", index=False)